### ISSUE TITLE
追加されると嬉しいなと思う個人的な３つの機能

### ISSUE THREAD

**Issue by hanpen72** [DoranekoSystems/Tsubame#3]
１，Byte配列での検索　（例：「BC 30 17 41 72 28 88 3A」
→こちら既にあったらすみません。regexあたりの機能でいけますかね＠＠？

２，検索するメモリー範囲の指定
→ある程度検索したいメモリー範囲が絞れている場合もあるので、その場合に全メモリーではなく指定したメモリー範囲の検索が行えると便利かなと思い＞＜

３，nearby検索
→ファースト条件でヒットしたメモリから指定したメモリ範囲をセカンド条件で検索みたいなイメージ＞＜

上記３つの機能あるとさらに自分的には使いやすくなるなと思い勝手ながらissue化してみました。
後々、自分でもプルリクだせるようにコード読み込んでみたいと思います。

**Comment by DoranekoSystems** [comment]
ご意見誠に有難うございます。

１，Byte配列での検索　（例：「BC 30 17 41 72 28 88 3A」
wildcard非対応ですが、追加しました。

またコードの整理と、同時に複数タイプの検索が可能な仕様は廃止しました。

**Comment by DoranekoSystems** [comment]
大変お待たせしました。
1,2,3ともに実装してみました。
aobscanはワイルドカードに対応しています。(BC 30 17 41 ?? 28 ?? 3A)

https://github.com/DoranekoSystems/Tsubame/wiki/Command-List

**Comment by DoranekoSystems** [comment]
@hanpen72 
一旦閉めさせていただきます。
意図と違う点などあれば、是非お伝えいただけると嬉しいです。
